# Production Environment Configuration
app:
  name: "DevEagles Analytics"
  version: "0.1.0"
  debug: false
  log_level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false

database:
  crm:
    url: "${ANALYTICS_CRM_DATABASE_URL}" # 환경변수에서 가져옴
    pool_size: 20
    max_overflow: 30
  analytics:
    url: "data/analytics_local.db" # 통일된 DB 경로
    pool_size: 8
    max_overflow: 0

etl:
  batch_size: 10000
  incremental: true
  timestamp_file: "/data/last_etl.txt"

ml:
  model_storage_path: "/models"
  retrain_threshold: 0.05
  feature_columns:
    - "age"
    - "frequency"
    - "avg_monetary"
    - "lifecycle_days"
    - "service_variety"
    - "employee_variety"
    - "visits_3m"

scheduling:
  jobstore_url: "${ANALYTICS_SCHEDULER_JOBSTORE_URL}"
  etl_schedule_hour: 2
  tagging_schedule_hour: 4 # ETL 완료 후 2시간 간격
  training_schedule_day: "sun"
  training_schedule_hour: 6 # 더 넉넉한 간격

customer_segmentation:
  new_customer_visit_threshold: 3
  growing_customer_visit_threshold: 10
  vip_customer_amount_threshold: 100000

risk_assessment:
  new_customer_followup_days: 7
  new_customer_risk_days: 20
  reactivation_needed_days: 30
  growing_customer_delay_multiplier: 1.5
  loyal_customer_delay_multiplier: 2.0

api:
  prefix: "/api/v1"
  docs_url: null # 프로덕션에서는 docs 비활성화
  redoc_url: null
  openapi_url: null

security:
  secret_key: "${ANALYTICS_SECRET_KEY}" # 환경변수 필수
  access_token_expire_minutes: 30
  algorithm: "HS256"

monitoring:
  enable_metrics: true
  metrics_path: "/metrics"
  enable_tracing: false # 프로덕션에서는 성능상 비활성화

external_services:
  workflow_service_url: "${ANALYTICS_WORKFLOW_SERVICE_URL}"
  notification_webhook_url: "${ANALYTICS_NOTIFICATION_WEBHOOK_URL}"
