# Staging Environment Configuration
app:
  name: "DevEagles Analytics (Staging)"
  version: "0.1.0"
  debug: false
  log_level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000
  workers: 2
  reload: false

database:
  crm:
    url: "${ANALYTICS_CRM_DATABASE_URL}"
    pool_size: 10
    max_overflow: 20
  analytics:
    url: "data/analytics_local.db"
    pool_size: 6
    max_overflow: 0

etl:
  batch_size: 5000
  incremental: true
  timestamp_file: "data/last_etl.txt"

ml:
  model_storage_path: "models"
  retrain_threshold: 0.05
  feature_columns:
    - "age"
    - "frequency"
    - "avg_monetary"
    - "lifecycle_days"
    - "service_variety"
    - "employee_variety"
    - "visits_3m"

scheduling:
  jobstore_url: "sqlite:///data/scheduler.db"
  etl_schedule_hour: 2
  tagging_schedule_hour: 4 # ETL 완료 후 2시간 간격
  training_schedule_day: "sun"
  training_schedule_hour: 6 # 더 넉넉한 간격

customer_segmentation:
  new_customer_visit_threshold: 3
  growing_customer_visit_threshold: 10
  vip_customer_amount_threshold: 100000

risk_assessment:
  new_customer_followup_days: 7
  new_customer_risk_days: 20
  reactivation_needed_days: 30
  growing_customer_delay_multiplier: 1.5
  loyal_customer_delay_multiplier: 2.0

api:
  prefix: "/api/v1"
  docs_url: "/docs" # 스테이징에서는 docs 활성화
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"

security:
  secret_key: "${ANALYTICS_SECRET_KEY}"
  access_token_expire_minutes: 30
  algorithm: "HS256"

monitoring:
  enable_metrics: true
  metrics_path: "/metrics"
  enable_tracing: true # 스테이징에서는 디버깅을 위해 활성화

external_services:
  workflow_service_url: "${ANALYTICS_WORKFLOW_SERVICE_URL}"
  notification_webhook_url: "${ANALYTICS_NOTIFICATION_WEBHOOK_URL}"
  be_api_url: "${ANALYTICS_BE_API_URL}"
  be_api_timeout: 30
