name: 개발환경 / 도구 개선
description: 빌드, 배포, 도구 설정 등 개발환경을 개선합니다
title: "[도메인명] 환경/도구명 - 간단한 설명"
labels: ["chore"]
type: "Task"
projects: ["deveagles-final"]
assignees: []
body:
  - type: dropdown
    id: area
    attributes:
      label: 개발 영역
      description: 백엔드/프론트엔드 중 해당 영역을 선택해주세요
      options:
        - Backend
        - Frontend
        - Full Stack
        - DevOps/Infra
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🔧 개선 내용
      description: 어떤 개발환경이나 도구를 개선할 것인지 설명해주세요
      placeholder: |
        - 개선하려는 환경/도구: (예: 빌드 시스템, CI/CD, 라이브러리 등)
        - 현재 문제점: 
        - 개선 방향:
        - 기대 효과:
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 개선 체크리스트
      description: 개선 과정에서 확인해야 할 항목들입니다
      options:
        - label: 현재 상태 분석 완료
        - label: 개선 방안 검토 완료
        - label: 구현/설정 완료
        - label: 테스트 및 검증 완료
