name: Auto-assign issue creator
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const creator = issue.user.login;

            // 이슈 생성자를 assignee로 할당
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: issue.number,
              assignees: [creator]
            });

            console.log(`Assigned issue #${issue.number} to creator: ${creator}`);
