name: Notify Assignee on Bug Issue Created

on:
  issues:
    types: [assigned]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug')

    steps:
      - name: Wait for issue to settle
        run: sleep 2

      - name: Check if issue has assignee
        id: check-assignee
        run: |
          if [ "${{ github.event.issue.assignee }}" != "null" ] && [ -n "${{ github.event.issue.assignee.login }}" ]; then
            echo "has_assignee=true" >> "$GITHUB_OUTPUT"
            echo "assignee_login=${{ github.event.issue.assignee.login }}" >> "$GITHUB_OUTPUT"
          else
            echo "has_assignee=false" >> "$GITHUB_OUTPUT"
            echo "⚠️ No assignee found for this bug issue"
          fi

      - name: Map GitHub username to Discord ID
        if: steps.check-assignee.outputs.has_assignee == 'true'
        id: map-assignee
        env:
          ASSIGNEE_LOGIN: ${{ steps.check-assignee.outputs.assignee_login }}
        run: |
          echo "🔄 Mapping GitHub assignee to Discord mention..."

          declare -A USER_MAP=(
            ["64etuor"]="637937081875824650"
            ["wishbornDev"]="1313511515407777865"
            ["gyeongmin03"]="377380180467122178"
            ["hwan1023"]="963059572812157010"
            ["nineeko"]="821058142795333655"
            ["Jayboo816"]="1326066071676915763"
          )

          DISCORD_ID=${USER_MAP[$ASSIGNEE_LOGIN]}

          if [ -n "$DISCORD_ID" ]; then
            echo "mention=<@$DISCORD_ID>" >> "$GITHUB_OUTPUT"
            echo "✅ Mapped $ASSIGNEE_LOGIN to Discord ID: $DISCORD_ID"
          else
            echo "mention=" >> "$GITHUB_OUTPUT"
            echo "⚠️ No Discord ID mapped for $ASSIGNEE_LOGIN"
          fi

      - name: Send Discord Notification
        if: steps.check-assignee.outputs.has_assignee == 'true'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_REQUEST_WEBHOOK_URL }}
          MENTION: ${{ steps.map-assignee.outputs.mention }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.repository }}
          ASSIGNEE_NAME: ${{ github.event.issue.assignee.login }}
          ASSIGNEE_AVATAR: ${{ github.event.issue.assignee.avatar_url }}
          AUTHOR_NAME: ${{ github.event.issue.user.login }}
          AUTHOR_AVATAR: ${{ github.event.issue.user.avatar_url }}
          CREATED_AT: ${{ github.event.issue.created_at }}
        run: |
          # Format the current time in a readable format
          FORMATTED_DATE=$(date "+%Y년 %m월 %d일 %H:%M")

          # 이슈 라벨들 가져오기
          LABELS="${{ join(github.event.issue.labels.*.name, ', ') }}"

          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🚨 $MENTION님! 수정 요청 티켓이 발행되었습니다.\",
            \"embeds\": [
              {
                \"title\": \"🐛 수정 요청 티켓 (클릭하여 이슈로 이동)\",
                \"url\": \"$ISSUE_URL\",
                \"color\": 15158332,
                \"fields\": [
                  {
                    \"name\": \"🔖 요약\",
                    \"value\": \"**$ISSUE_TITLE**\",
                    \"inline\": false
                  },
                  {
                    \"name\": \"📋 요청자\",
                    \"value\": \"@$AUTHOR_NAME\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"👤 담당자\",
                    \"value\": \"$MENTION\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"📅 이슈 번호\",
                    \"value\": \"**#$ISSUE_NUMBER**\",
                    \"inline\": true
                  }
                ],
                \"footer\": {
                  \"text\": \"* 담당자는 티켓 확인 시 ✅ 반드시 체크해주세요.*\",
                  \"icon_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\"
                },
                \"timestamp\": \"$CREATED_AT\"
              }
            ],
            \"allowed_mentions\": {
              \"parse\": [\"users\"]
            }
          }" \
          "$DISCORD_WEBHOOK_URL"
