name: Deploy Python Server to DockerHub and AWS EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "be15_DevEagles_DA/**"

jobs:
  build-and-push:
    name: Build and Push Python Server to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./be15_DevEagles_DA
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:latest
          no-cache: true

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi
            
            # Install Docker Compose if not exists
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Create deployment directory
            mkdir -p /home/ec2-user/deveagles-da
            cd /home/ec2-user/deveagles-da
            
            # Create docker-compose.yml
            cat > docker-compose.yml << 'EOF'
            version: '3.8'
            services:
              deveagles-da:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:latest
                container_name: deveagles-da
                ports:
                  - "80:8080"
                  - "8050:8050"
                  - "8000:8000"
                environment:
                  - CRM_DATABASE_URL=mysql+pymysql://${{ secrets.RDS_USERNAME }}:${{ secrets.RDS_PASSWORD }}@${{ secrets.RDS_HOSTNAME }}:${{ secrets.RDS_PORT }}/${{ secrets.RDS_DB_NAME }}?charset=utf8mb4
                  - ANALYTICS_DB_PATH=/opt/airflow/data/analytics.duckdb
                  - LOG_LEVEL=INFO
                  - DEBUG=false
                  - SSL_CA_CERT_PATH=/opt/ssl/rds-ca-2019-root.pem
                  - SSL_VERIFY_CERT=true
                volumes:
                  - ./data:/opt/airflow/data
                  - ./logs:/opt/airflow/logs
                restart: always
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 30s
            EOF
            
            # Create data and logs directories
            mkdir -p data logs
            
            # Stop and remove existing container
            sudo docker-compose down || true
            
            # Pull latest image and start
            sudo docker-compose pull
            sudo docker-compose up -d
            
            # Wait for container to be healthy
            echo "Waiting for container to be healthy..."
            timeout 300 bash -c 'until sudo docker-compose ps | grep -q "healthy\|Up"; do sleep 5; done' || {
              echo "Container failed to start properly"
              sudo docker-compose logs
              exit 1
            }
            
            echo "Deployment completed successfully!"
            sudo docker-compose ps