name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: "be15_DevEagles_FE/package-lock.json"

      - name: Install dependencies
        working-directory: ./be15_DevEagles_FE
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./be15_DevEagles_FE
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./be15_DevEagles_FE
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: be15_DevEagles_FE/playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-results
          path: be15_DevEagles_FE/test-results/
          retention-days: 30
