name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./be15_DevEagles_FE/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./be15_DevEagles_FE/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Debug file structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la
          echo "be15_DevEagles_FE contents:"
          ls -la be15_DevEagles_FE/
          echo "Checking package files:"
          ls -la be15_DevEagles_FE/package*

      - name: Install dependencies
        working-directory: be15_DevEagles_FE
        run: |
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json, using npm ci"
            npm ci
          else
            echo "No package-lock.json found, using npm install"
            npm install
          fi

      - name: Install Playwright Browsers
        working-directory: be15_DevEagles_FE
        run: npx playwright install --with-deps

      - name: Build application
        working-directory: be15_DevEagles_FE
        run: npm run build

      - name: Run Playwright tests
        working-directory: be15_DevEagles_FE
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./be15_DevEagles_FE/playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-results
          path: ./be15_DevEagles_FE/test-results/
          retention-days: 30
