# .github/workflows/copy-issue-body.yml
name: copy issue body to PR
on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  sync-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr      = context.payload.pull_request;

            // PR 타이틀과 브랜치명에서 이슈 번호 찾기
            const titleNumbers = pr.title.match(/#(\d+)/g) || [];
            const branchNumbers = pr.head.ref.match(/(\d+)/g) || [];

            let issueNo = null;

            // 우선순위: PR 타이틀 > 브랜치명
            if (titleNumbers.length > 0) {
              issueNo = titleNumbers[0].replace('#', '');
              console.log(`Found issue number in PR title: ${issueNo}`);
            } else if (branchNumbers.length > 0) {
              issueNo = branchNumbers[0];
              console.log(`Found issue number in branch name: ${issueNo}`);
            }

            if (!issueNo) {
              console.log('No issue number found in PR title or branch name');
              return;
            }

            try {
              const {data: issue} = await github.rest.issues.get({
                ...context.repo,
                issue_number: issueNo
              });
              
              // 체크리스트 분석
              const checkboxes = issue.body.match(/- \[([ x])\]/g) || [];
              const totalChecks = checkboxes.length;
              const completedChecks = checkboxes.filter(cb => cb.includes('[x]')).length;
              const isComplete = totalChecks > 0 && completedChecks === totalChecks;
              
              let checklistStatus = '';
              if (totalChecks > 0) {
                checklistStatus = `\n\n## 🔍 이슈 체크리스트 상태\n${isComplete ? '✅' : '⚠️'} **${completedChecks}/${totalChecks} 완료** ${isComplete ? '(모든 항목 완료!)' : '(미완료 항목 있음)'}\n`;
              }
              
              const newBody = `${issue.body}${checklistStatus}\n\n---\n\n${pr.body || ''}`;
              await github.rest.pulls.update({
                ...context.repo,
                pull_number: pr.number,
                body: newBody
              });
              console.log('Successfully updated PR body with issue context');
            } catch (error) {
              console.error(`Failed to process issue #${issueNo}:`, error.message);
            }
