name: Scheduled Build Test

on:
  # schedule:
  #   # 1시간마다 실행
  #   - cron: "0 */1 * * *"
  workflow_dispatch: # 수동 트리거 허용

jobs:
  build-backend:
    name: 백엔드 빌드 테스트
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Gradle 파일 확인
        run: |
          echo "백엔드 디렉토리 구조 확인:"
          ls -la ./be15_DevEagles_BE
          echo "Gradle 파일 확인:"
          ls -la ./be15_DevEagles_BE/gradle
          echo "Gradle wrapper 확인:"
          ls -la ./be15_DevEagles_BE/gradle/wrapper

      - name: Gradle wrapper jar 다운로드
        run: |
          mkdir -p ./be15_DevEagles_BE/gradle/wrapper
          wget -O ./be15_DevEagles_BE/gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.3.0/gradle/wrapper/gradle-wrapper.jar
          chmod +x ./be15_DevEagles_BE/gradlew
          ls -la ./be15_DevEagles_BE/gradle/wrapper

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('be15_DevEagles_BE/**/*.gradle*', 'be15_DevEagles_BE/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 빌드
        working-directory: ./be15_DevEagles_BE
        run: |
          # 간단한 빌드만 시도
          ./gradlew -v
          ./gradlew tasks
        continue-on-error: true
        id: gradle-build

      - name: 빌드 상태 확인
        id: build-status
        run: |
          if ${{ steps.gradle-build.outcome == 'success' }}; then
            echo "status=성공" >> $GITHUB_OUTPUT
          else
            echo "status=실패" >> $GITHUB_OUTPUT
          fi

      - name: Discord에 백엔드 빌드 결과 전송
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.BUILDTEST_DISCORD_WEBHOOK_URL }}
          title: "백엔드 빌드 테스트 결과"
          description: "백엔드 빌드 상태: ${{ steps.build-status.outputs.status }}"
          color: ${{ steps.gradle-build.outcome == 'Result:' && '0x00ff00' || '0xff0000' }}
          status: ${{ steps.gradle-build.outcome }}
          content: ${{ steps.gradle-build.outcome != 'Result:' && ' 백엔드 빌드가 실패했습니다!' || '' }}

  build-frontend:
    name: 프론트엔드 빌드 테스트
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 프론트엔드 파일 생성
        run: |
          echo "프론트엔드 디렉토리 구조 확인:"
          ls -la ./be15_DevEagles_FE
          echo "프론트엔드 src 디렉토리 구조 확인:"
          ls -la ./be15_DevEagles_FE/src
          # 실제 파일들이 이미 존재하므로, 더미 파일 생성 로직은 제거합니다.
          # 필요하다면 실제 assets 및 components 디렉토리 내용을 확인할 수 있습니다.
          echo "실제 src/assets 디렉토리 내용:"
          ls -la ./be15_DevEagles_FE/src/assets || echo "src/assets 디렉토리가 없거나 비어있습니다."
          echo "실제 src/components 디렉토리 내용:"
          ls -la ./be15_DevEagles_FE/src/components || echo "src/components 디렉토리가 없거나 비어있습니다."

      - name: NPM 캐시 설정
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('be15_DevEagles_FE/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 의존성 설치
        working-directory: ./be15_DevEagles_FE
        run: npm install
        continue-on-error: true
        id: npm-install

      - name: 빌드 실행
        working-directory: ./be15_DevEagles_FE
        run: npm run build
        continue-on-error: true
        id: npm-build

      - name: 빌드 상태 확인
        id: fe-build-status
        run: |
          if ${{ steps.npm-build.outcome == 'success' }}; then
            echo "status=성공" >> $GITHUB_OUTPUT
          else
            echo "status=실패" >> $GITHUB_OUTPUT
          fi

      - name: Discord에 프론트엔드 빌드 결과 전송
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.BUILDTEST_DISCORD_WEBHOOK_URL }}
          title: "프론트엔드 빌드 테스트 결과"
          description: "프론트엔드 빌드 상태: ${{ steps.fe-build-status.outputs.status }}"
          color: ${{ steps.npm-build.outcome == 'Result:' && '0x00ff00' || '0xff0000' }}
          status: ${{ steps.npm-build.outcome }}
          content: ${{ steps.npm-build.outcome != 'Result:' && ' 프론트엔드 빌드가 실패했습니다!' || '' }}
